### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-3114

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#100]
In [CVE-2021-3114](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2021/3xxx/CVE-2021-3114.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: Go Standard Library (package not identified)
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  In Go before 1.14.14 and 1.15.x before 1.15.7, crypto/elliptic/p224.go can generate incorrect outputs, related to an underflow of the lowest limb during the final complete reduction in the P-224 field.

cve: CVE-2021-3114
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
