### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-31525

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#101]
In [CVE-2021-31525](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2021/31xxx/CVE-2021-31525.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: Go Standard Library (package not identified)
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  net/http in Go before 1.15.12 and 1.16.x before 1.16.4 allows remote attackers to cause a denial of service (panic) via a large header to ReadRequest or ReadResponse. Server, Transport, and Client can each be affected in some configurations.

cve: CVE-2021-31525
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
