### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-32721

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#102]
In [CVE-2021-32721](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2021/32xxx/CVE-2021-32721.json), the reference URL [github.com/AndrewBurian/powermux](github.com/AndrewBurian/powermux) (and possibly others) refers to something in Go.

```
module: github.com/AndrewBurian/powermux
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  PowerMux is a drop-in replacement for Go's http.ServeMux. In PowerMux versions prior to 1.1.1, attackers may be able to craft phishing links and other open redirects by exploiting the trailing slash redirection feature. This may lead to users being redirected to untrusted sites after following an attacker crafted link. The issue is resolved in v1.1.1. There are no existing workarounds.

cve: CVE-2021-32721
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
