### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-33194

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#103]
In [CVE-2021-33194](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2021/33xxx/CVE-2021-33194.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: Go Standard Library (package not identified)
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  golang.org/x/net before v0.0.0-20210520170846-37e1c6afe023 allows attackers to cause a denial of service (infinite loop) via crafted ParseFragment input.

cve: CVE-2021-33194
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
