### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-33195

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#104]
In [CVE-2021-33195](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2021/33xxx/CVE-2021-33195.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: Go Standard Library (package not identified)
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  Go before 1.15.13 and 1.16.x before 1.16.5 has functions for DNS lookups that do not validate replies from DNS servers, and thus a return value may contain an unsafe injection (e.g., XSS) that does not conform to the RFC1035 format.

cve: CVE-2021-33195
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
