### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-33197

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#106]
In [CVE-2021-33197](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2021/33xxx/CVE-2021-33197.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: Go Standard Library (package not identified)
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  In Go before 1.15.13 and 1.16.x before 1.16.5, some configurations of ReverseProxy (from net/http/httputil) result in a situation where an attacker is able to drop arbitrary headers.

cve: CVE-2021-33197
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
