### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-33198

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#107]
In [CVE-2021-33198](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2021/33xxx/CVE-2021-33198.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: Go Standard Library (package not identified)
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  In Go before 1.15.13 and 1.16.x before 1.16.5, there can be a panic for a large exponent to the math/big.Rat SetString or UnmarshalText method.

cve: CVE-2021-33198
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
