### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-34558

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#108]
In [CVE-2021-34558](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2021/34xxx/CVE-2021-34558.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: Go Standard Library (package not identified)
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  The crypto/tls package of Go through 1.16.5 does not properly assert that the type of public key in an X.509 certificate matches the expected type when doing a RSA based key exchange, allowing a malicious TLS server to cause a TLS client to panic.

cve: CVE-2021-34558
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
