### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-3538

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#109]
In [CVE-2021-3538](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2021/3xxx/CVE-2021-3538.json), the reference URL [Path is unknown](Path is unknown) (and possibly others) refers to something in Go.

```
module: Path is unknown
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  A flaw was found in github.com/satori/go.uuid in versions from commit 0ef6afb2f6cdd6cdaeee3885a95099c63f18fc8c to d91630c8510268e75203009fe7daf2b8e1d60c45. Due to insecure randomness in the g.rand.Read function the generated UUIDs are predictable for an attacker.

cve: CVE-2021-3538
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
