### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-36221

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#110]
In [CVE-2021-36221](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2021/36xxx/CVE-2021-36221.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: Go Standard Library (package not identified)
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  Go before 1.15.15 and 1.16.x before 1.16.7 has a race condition that can lead to a net/http/httputil ReverseProxy panic upon an ErrAbortHandler abort.

cve: CVE-2021-36221
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
