### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-38182

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#112]
In [CVE-2021-38182](https://github.com/CVEProject/cvelist/tree/42a143637353e9550882ee2846b7d04e813bc7c0/2021/38xxx/CVE-2021-38182.json), the reference URL [github.com/kyma-project/kyma](github.com/kyma-project/kyma) (and possibly others) refers to something in Go.

```
module: github.com/kyma-project/kyma
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  

cve: CVE-2021-38182
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
