### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-38297

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#113]
In [CVE-2021-38297](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2021/38xxx/CVE-2021-38297.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: Go Standard Library (package not identified)
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  Go before 1.16.9 and 1.17.x before 1.17.2 has a Buffer Overflow via large arguments in a function invocation from a WASM module, when GOARCH=wasm GOOS=js is used.

cve: CVE-2021-38297
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
