### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-3907

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#114]
In [CVE-2021-3907](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2021/3xxx/CVE-2021-3907.json), the reference URL [github.com/cloudflare/cfrpki](github.com/cloudflare/cfrpki) (and possibly others) refers to something in Go.

```
module: github.com/cloudflare/cfrpki
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  OctoRPKI does not escape a URI with a filename containing "..", this allows a repository to create a file, (ex. rsync://example.org/repo/../../etc/cron.daily/evil.roa), which would then be written to disk outside the base cache folder. This could allow for remote code execution on the host machine OctoRPKI is running on.

cve: CVE-2021-3907
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
