### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-3908

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#115]
In [CVE-2021-3908](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2021/3xxx/CVE-2021-3908.json), the reference URL [github.com/cloudflare/cfrpki](github.com/cloudflare/cfrpki) (and possibly others) refers to something in Go.

```
module: github.com/cloudflare/cfrpki
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  OctoRPKI does not limit the depth of a certificate chain, allowing for a CA to create children in an ad-hoc fashion, thereby making tree traversal never end.

cve: CVE-2021-3908
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
