### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-3909

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#116]
In [CVE-2021-3909](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2021/3xxx/CVE-2021-3909.json), the reference URL [github.com/cloudflare/cfrpki](github.com/cloudflare/cfrpki) (and possibly others) refers to something in Go.

```
module: github.com/cloudflare/cfrpki
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  OctoRPKI does not limit the length of a connection, allowing for a slowloris DOS attack to take place which makes OctoRPKI wait forever. Specifically, the repository that OctoRPKI sends HTTP requests to will keep the connection open for a day before a response is returned, but does keep drip feeding new bytes to keep the connection alive.

cve: CVE-2021-3909
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
