### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-3910

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#117]
In [CVE-2021-3910](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2021/3xxx/CVE-2021-3910.json), the reference URL [github.com/cloudflare/cfrpki](github.com/cloudflare/cfrpki) (and possibly others) refers to something in Go.

```
module: github.com/cloudflare/cfrpki
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  OctoRPKI crashes when encountering a repository that returns an invalid ROA (just an encoded NUL (\0) character).

cve: CVE-2021-3910
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
