### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-3911

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#118]
In [CVE-2021-3911](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2021/3xxx/CVE-2021-3911.json), the reference URL [github.com/cloudflare/cfrpki](github.com/cloudflare/cfrpki) (and possibly others) refers to something in Go.

```
module: github.com/cloudflare/cfrpki
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  If the ROA that a repository returns contains too many bits for the IP address then OctoRPKI will crash.

cve: CVE-2021-3911
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
