### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-39137

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#120]
In [CVE-2021-39137](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2021/39xxx/CVE-2021-39137.json), the reference URL [github.com/ethereum/go-ethereum](github.com/ethereum/go-ethereum) (and possibly others) refers to something in Go.

```
module: github.com/ethereum/go-ethereum
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  go-ethereum is the official Go implementation of the Ethereum protocol. In affected versions a consensus-vulnerability in go-ethereum (Geth) could cause a chain split, where vulnerable versions refuse to accept the canonical chain. Further details about the vulnerability will be disclosed at a later date. A patch is included in the upcoming `v1.10.8` release. No workaround are available.

cve: CVE-2021-39137
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
