### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-39183

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#121]
In [CVE-2021-39183](https://github.com/CVEProject/cvelist/tree/42a143637353e9550882ee2846b7d04e813bc7c0/2021/39xxx/CVE-2021-39183.json), the reference URL [github.com/owncast/owncast](github.com/owncast/owncast) (and possibly others) refers to something in Go.

```
module: github.com/owncast/owncast
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  

cve: CVE-2021-39183
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
