### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-39939

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#122]
In [CVE-2021-39939](https://github.com/CVEProject/cvelist/tree/42a143637353e9550882ee2846b7d04e813bc7c0/2021/39xxx/CVE-2021-39939.json), the reference URL [gitlab.com/gitlab-org/gitlab-runner](gitlab.com/gitlab-org/gitlab-runner) (and possibly others) refers to something in Go.

```
module: gitlab.com/gitlab-org/gitlab-runner
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  

cve: CVE-2021-39939
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
