### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-41090

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#123]
In [CVE-2021-41090](https://github.com/CVEProject/cvelist/tree/42a143637353e9550882ee2846b7d04e813bc7c0/2021/41xxx/CVE-2021-41090.json), the reference URL [github.com/grafana/agent](github.com/grafana/agent) (and possibly others) refers to something in Go.

```
module: github.com/grafana/agent
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  

cve: CVE-2021-41090
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
