### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-41135

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#124]
In [CVE-2021-41135](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2021/41xxx/CVE-2021-41135.json), the reference URL [github.com/cosmos/cosmos-sdk](github.com/cosmos/cosmos-sdk) (and possibly others) refers to something in Go.

```
module: github.com/cosmos/cosmos-sdk
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  The Cosmos-SDK is a framework for building blockchain applications in Golang. Affected versions of the SDK were vulnerable to a consensus halt due to non-deterministic behaviour in a ValidateBasic method in the x/authz module. The MsgGrant of the x/authz module contains a Grant field which includes a user-defined expiration time for when the authorization grant expires. In Grant.ValidateBasic(), that time is compared to the node’s local clock time. Any chain running an affected version of the SDK with the authz module enabled could be halted by anyone with the ability to send transactions on that chain. Recovery would require applying the patch and rolling back the latest block. Users are advised to update to version 0.44.2.

cve: CVE-2021-41135
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
