### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-41173

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#125]
In [CVE-2021-41173](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2021/41xxx/CVE-2021-41173.json), the reference URL [github.com/ethereum/go-ethereum](github.com/ethereum/go-ethereum) (and possibly others) refers to something in Go.

```
module: github.com/ethereum/go-ethereum
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  Go Ethereum is the official Golang implementation of the Ethereum protocol. Prior to version 1.10.9, a vulnerable node is susceptible to crash when processing a maliciously crafted message from a peer. Version v1.10.9 contains patches to the vulnerability. There are no known workarounds aside from upgrading.

cve: CVE-2021-41173
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
