### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-41190

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#126]
In [CVE-2021-41190](https://github.com/CVEProject/cvelist/tree/42a143637353e9550882ee2846b7d04e813bc7c0/2021/41xxx/CVE-2021-41190.json), the reference URL [github.com/opencontainers/distribution-spec](github.com/opencontainers/distribution-spec) (and possibly others) refers to something in Go.

```
module: github.com/opencontainers/distribution-spec
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  The OCI Distribution Spec project defines an API protocol to facilitate and standardize the distribution of content. In the OCI Distribution Specification version 1.0.0 and prior, the Content-Type header alone was used to determine the type of document during push and pull operations. Documents that contain both “manifests” and “layers” fields could be interpreted as either a manifest or an index in the absence of an accompanying Content-Type header. If a Content-Type header changed between two pulls of the same digest, a client may interpret the resulting content differently. The OCI Distribution Specification has been updated to require that a mediaType value present in a manifest or index match the Content-Type header used during the push and pull operations. Clients pulling from a registry may distrust the Content-Type header and reject an ambiguous document that contains both “manifests” and “layers” fields or “manifests” and “config” fields if they are unable to update to version 1.0.1 of the spec.

cve: CVE-2021-41190
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
