### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-41230

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#127]
In [CVE-2021-41230](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2021/41xxx/CVE-2021-41230.json), the reference URL [github.com/pomerium/pomerium](github.com/pomerium/pomerium) (and possibly others) refers to something in Go.

```
module: github.com/pomerium/pomerium
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  Pomerium is an open source identity-aware access proxy. In affected versions changes to the OIDC claims of a user after initial login are not reflected in policy evaluation when using `allowed_idp_claims` as part of policy. If using `allowed_idp_claims` and a user's claims are changed, Pomerium can make incorrect authorization decisions. This issue has been resolved in v0.15.6. For users unable to upgrade clear data on `databroker` service by clearing redis or restarting the in-memory databroker to force claims to be updated.

cve: CVE-2021-41230
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
