### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-41244

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#128]
In [CVE-2021-41244](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2021/41xxx/CVE-2021-41244.json), the reference URL [github.com/grafana/grafana](github.com/grafana/grafana) (and possibly others) refers to something in Go.

```
module: github.com/grafana/grafana
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  Grafana is an open-source platform for monitoring and observability. In affected versions when the fine-grained access control beta feature is enabled and there is more than one organization in the Grafana instance admins are able to access users from other organizations. Grafana 8.0 introduced a mechanism which allowed users with the Organization Admin role to list, add, remove, and update users’ roles in other organizations in which they are not an admin. With fine-grained access control enabled, organization admins can list, add, remove and update users' roles in another organization, where they do not have organization admin role. All installations between v8.0 and v8.2.3 that have fine-grained access control beta enabled and more than one organization should be upgraded as soon as possible. If you cannot upgrade, you should turn off the fine-grained access control using a feature flag.

cve: CVE-2021-41244
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
