### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-41278

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#131]
In [CVE-2021-41278](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2021/41xxx/CVE-2021-41278.json), the reference URL [github.com/edgexfoundry/app-functions-sdk-go](github.com/edgexfoundry/app-functions-sdk-go) (and possibly others) refers to something in Go.

```
module: github.com/edgexfoundry/app-functions-sdk-go
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  Functions SDK for EdgeX is meant to provide all the plumbing necessary for developers to get started in processing/transforming/exporting data out of the EdgeX IoT platform. In affected versions broken encryption in app-functions-sdk “AES” transform in EdgeX Foundry releases prior to Jakarta allows attackers to decrypt messages via unspecified vectors. The app-functions-sdk exports an “aes” transform that user scripts can optionally call to encrypt data in the processing pipeline. No decrypt function is provided. Encryption is not enabled by default, but if used, the level of protection may be less than the user may expects due to a broken implementation. Version v2.1.0 (EdgeX Foundry Jakarta release and later) of app-functions-sdk-go/v2 deprecates the “aes” transform and provides an improved “aes256” transform in its place. The broken implementation will remain in a deprecated state until it is removed in the next EdgeX major release to avoid breakage of existing software that depends on the broken implementation. As the broken transform is a library function that is not invoked by default, users who do not use the AES transform in their processing pipelines are unaffected. Those that are affected are urged to upgrade to the Jakarta EdgeX release and modify processing pipelines to use the new "aes256" transform.

cve: CVE-2021-41278
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
