### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-41771

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#132]
In [CVE-2021-41771](https://github.com/CVEProject/cvelist/tree/42a143637353e9550882ee2846b7d04e813bc7c0/2021/41xxx/CVE-2021-41771.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: Go Standard Library (package not identified)
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  ImportedSymbols in debug/macho (for Open or OpenFat) in Go before 1.16.10 and 1.17.x before 1.17.3 Accesses a Memory Location After the End of a Buffer, aka an out-of-bounds slice situation.

cve: CVE-2021-41771
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
