### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-41772

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#133]
In [CVE-2021-41772](https://github.com/CVEProject/cvelist/tree/42a143637353e9550882ee2846b7d04e813bc7c0/2021/41xxx/CVE-2021-41772.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: Go Standard Library (package not identified)
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  Go before 1.16.10 and 1.17.x before 1.17.3 allows an archive/zip Reader.Open panic via a crafted ZIP archive containing an invalid name or an empty filename field.

cve: CVE-2021-41772
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
