### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-42836

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#134]
In [CVE-2021-42836](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2021/42xxx/CVE-2021-42836.json), the reference URL [github.com/tidwall/gjson](github.com/tidwall/gjson) (and possibly others) refers to something in Go.

```
module: github.com/tidwall/gjson
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  GJSON before 1.9.3 allows a ReDoS (regular expression denial of service) attack.

cve: CVE-2021-42836
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
