### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-43669

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#136]
In [CVE-2021-43669](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2021/43xxx/CVE-2021-43669.json), the reference URL [github.com/hyperledger/fabric](github.com/hyperledger/fabric) (and possibly others) refers to something in Go.

```
module: github.com/hyperledger/fabric
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  A vulnerability has been detected in HyperLedger Fabric v1.4.0, v2.0.0, v2.0.1, v2.3.0. It can easily break down as many orderers as the attacker wants. This bug can be leveraged by constructing a message whose header is invalid to the interface Order. This bug has been admitted and fixed by the developers of Fabric.

cve: CVE-2021-43669
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
