### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-43784

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#137]
In [CVE-2021-43784](https://github.com/CVEProject/cvelist/tree/42a143637353e9550882ee2846b7d04e813bc7c0/2021/43xxx/CVE-2021-43784.json), the reference URL [github.com/opencontainers/runc](github.com/opencontainers/runc) (and possibly others) refers to something in Go.

```
module: github.com/opencontainers/runc
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  

cve: CVE-2021-43784
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
