### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-43815

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#140]
In [CVE-2021-43815](https://github.com/CVEProject/cvelist/tree/42a143637353e9550882ee2846b7d04e813bc7c0/2021/43xxx/CVE-2021-43815.json), the reference URL [github.com/grafana/grafana](github.com/grafana/grafana) (and possibly others) refers to something in Go.

```
module: github.com/grafana/grafana
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  

cve: CVE-2021-43815
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
