### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-43979

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#142]
In [CVE-2021-43979](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2021/43xxx/CVE-2021-43979.json), the reference URL [github.com/open-policy-agent/gatekeeper](github.com/open-policy-agent/gatekeeper) (and possibly others) refers to something in Go.

```
module: github.com/open-policy-agent/gatekeeper
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  ** DISPUTED ** Styra Open Policy Agent (OPA) Gatekeeper through 3.7.0 mishandles concurrency, sometimes resulting in incorrect access control. The data replication mechanism allows policies to access the Kubernetes cluster state. During data replication, OPA/Gatekeeper does not wait for the replication to finish before processing a request, which might cause inconsistencies between the replicated resources in OPA/Gatekeeper and the resources actually present in the cluster. Inconsistency can later be reflected in a policy bypass. NOTE: the vendor disagrees that this is a vulnerability, because Kubernetes states are only eventually consistent.

cve: CVE-2021-43979
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
