### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-43839

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#143]
In [CVE-2021-43839](https://github.com/CVEProject/cvelist/tree/4f3bd25bb0895e70279a65d50322de4f8cb21872/2021/43xxx/CVE-2021-43839.json), the reference URL [github.com/crypto-org-chain/cronos](github.com/crypto-org-chain/cronos) (and possibly others) refers to something in Go.

```
module: github.com/crypto-org-chain/cronos
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  

cve: CVE-2021-43839
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
