### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/h2o/h2o: CVE-2021-43848

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#159]
In [CVE-2021-43848](https://github.com/CVEProject/cvelist/tree/4ea21dc0de9810f415419d4f79b4107c275ca371/2021/43xxx/CVE-2021-43848.json), the reference URL [github.com/h2o/h2o](github.com/h2o/h2o) (and possibly others) refers to something in Go.
- Commit: https://github.com/h2o/h2o/commit/8c0eca3

```
module: github.com/h2o/h2o
package: h2o
description: |
    h2o is an open source http server. In code prior to the `8c0eca3` commit h2o may attempt to access uninitialized memory. When receiving QUIC frames in certain order, HTTP/3 server-side implementation of h2o can be misguided to treat uninitialized memory as HTTP/3 frames that have been received. When h2o is used as a reverse proxy, an attacker can abuse this vulnerability to send internal state of h2o to backend servers controlled by the attacker or third party. Also, if there is an HTTP endpoint that reflects the traffic sent from the client, an attacker can use that reflector to obtain internal state of h2o. This internal state includes traffic of other connections in unencrypted form and TLS session tickets. This vulnerability exists in h2o server with HTTP/3 support, between commit 93af138 and d1f0f65. None of the released versions of h2o are affected by this vulnerability. There are no known workarounds. Users of unreleased versions of h2o using HTTP/3 are advised to upgrade immediately.
cves:
  - CVE-2021-43848
links:
    commit: https://github.com/h2o/h2o/commit/8c0eca3
    context:
      - https://github.com/h2o/h2o/security/advisories/GHSA-f9xw-j925-m4m4

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
