### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2015-5741

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#25]
In [CVE-2015-5741](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2015/5xxx/CVE-2015-5741.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: Go Standard Library (package not identified)
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  

cve: CVE-2015-5741
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
