### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/garden-io/garden: CVE-2022-24829

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#284]
CVE-2022-24829 references [github.com/garden-io/garden](https://github.com/garden-io/garden), which may be a Go module.

Description:
Garden is an automation platform for Kubernetes development and testing. In versions prior to 0.12.39 multiple endpoints did not require authentication. In some operating modes this allows for an attacker to gain access to the application erroneously. The configuration is leaked through the /api endpoint on the local server that is responsible for serving the Garden dashboard.
At the moment, this server is accessible to 0.0.0.0 which makes it accessible to anyone on the same network (or anyone on the internet if they are on a public, static IP). This may lead to the ability to compromise credentials, secrets or environment variables. Users are advised to upgrade to version 0.12.39 as soon as possible. Users unable to upgrade should use a firewall blocking access to port 9777 from all untrusted network machines.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-24829
- JSON: https://github.com/CVEProject/cvelist/tree/25fb7ffd81f51e0f4f878733ae6a0adc3369f3f2/2022/24xxx/CVE-2022-24829.json
- Commit: https://github.com/garden-io/garden/commit/56051a5b50409227bc420910da88ed156a6e432b
- https://github.com/garden-io/garden/security/advisories/GHSA-f5f3-qrqw-2vqf

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
module: github.com/garden-io/garden
package: garden
description: |
    Garden is an automation platform for Kubernetes development and testing. In versions prior to 0.12.39 multiple endpoints did not require authentication. In some operating modes this allows for an attacker to gain access to the application erroneously. The configuration is leaked through the /api endpoint on the local server that is responsible for serving the Garden dashboard.
    At the moment, this server is accessible to 0.0.0.0 which makes it accessible to anyone on the same network (or anyone on the internet if they are on a public, static IP). This may lead to the ability to compromise credentials, secrets or environment variables. Users are advised to upgrade to version 0.12.39 as soon as possible. Users unable to upgrade should use a firewall blocking access to port 9777 from all untrusted network machines.
cves:
  - CVE-2022-24829
links:
    commit: https://github.com/garden-io/garden/commit/56051a5b50409227bc420910da88ed156a6e432b
    context:
      - https://github.com/garden-io/garden/security/advisories/GHSA-f5f3-qrqw-2vqf

```
