### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2016-3959

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#30]
In [CVE-2016-3959](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2016/3xxx/CVE-2016-3959.json), the reference URL [Go Standard Library](Go Standard Library) (and possibly others) refers to something in Go.

```
module: Go Standard Library
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  The Verify function in crypto/dsa/dsa.go in Go before 1.5.4 and 1.6.x before 1.6.1 does not properly check parameters passed to the big integer library, which might allow remote attackers to cause a denial of service (infinite loop) via a crafted public key to a program that uses HTTPS client certificates or SSH server libraries.

cve: CVE-2016-3959
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
