### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2016-4974

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#31]
In [CVE-2016-4974](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2016/4xxx/CVE-2016-4974.json), the reference URL [qpid.apache.org](qpid.apache.org) (and possibly others) refers to something in Go.

```
module: qpid.apache.org
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  Apache Qpid AMQP 0-x JMS client before 6.0.4 and JMS (AMQP 1.0) before 0.10.0 does not restrict the use of classes available on the classpath, which might allow remote authenticated users with permission to send messages to deserialize arbitrary objects and execute arbitrary code by leveraging a crafted serialized object in a JMS ObjectMessage that is handled by the getObject function.

cve: CVE-2016-4974
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
