### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2016-6254

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#32]
In [CVE-2016-6254](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2016/6xxx/CVE-2016-6254.json), the reference URL [collectd.org](collectd.org) (and possibly others) refers to something in Go.

```
module: collectd.org
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  Heap-based buffer overflow in the parse_packet function in network.c in collectd before 5.4.3 and 5.x before 5.5.2 allows remote attackers to cause a denial of service (daemon crash) or possibly execute arbitrary code via a crafted network packet.

cve: CVE-2016-6254
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
