### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2016-7547

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#33]
In [CVE-2016-7547](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2016/7xxx/CVE-2016-7547.json), the reference URL [github.com/rapid7/metasploit-framework](github.com/rapid7/metasploit-framework) (and possibly others) refers to something in Go.

```
module: github.com/rapid7/metasploit-framework
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  A command execution flaw on the Trend Micro Threat Discovery Appliance 2.6.1062r1 exists with the timezone parameter in the admin_sys_time.cgi interface.

cve: CVE-2016-7547
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
