### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2016-7552

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#34]
In [CVE-2016-7552](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2016/7xxx/CVE-2016-7552.json), the reference URL [github.com/rapid7/metasploit-framework](github.com/rapid7/metasploit-framework) (and possibly others) refers to something in Go.

```
module: github.com/rapid7/metasploit-framework
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  On the Trend Micro Threat Discovery Appliance 2.6.1062r1, directory traversal when processing a session_id cookie allows a remote, unauthenticated attacker to delete arbitrary files as root. This can be used to bypass authentication or cause a DoS.

cve: CVE-2016-7552
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
