### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2017-1000097

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#35]
In [CVE-2017-1000097](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2017/1000xxx/CVE-2017-1000097.json), the reference URL [Go Standard Library](Go Standard Library) (and possibly others) refers to something in Go.

```
module: Go Standard Library
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  On Darwin, user's trust preferences for root certificates were not honored. If the user had a root certificate loaded in their Keychain that was explicitly not trusted, a Go program would still verify a connection using that root certificate.

cve: CVE-2017-1000097
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
