### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2017-1000098

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#36]
In [CVE-2017-1000098](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2017/1000xxx/CVE-2017-1000098.json), the reference URL [Go Standard Library](Go Standard Library) (and possibly others) refers to something in Go.

```
module: Go Standard Library
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  The net/http package's Request.ParseMultipartForm method starts writing to temporary files once the request body size surpasses the given "maxMemory" limit. It was possible for an attacker to generate a multipart request crafted such that the server ran out of file descriptors.

cve: CVE-2017-1000098
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
