### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2017-13872

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#37]
In [CVE-2017-13872](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2017/13xxx/CVE-2017-13872.json), the reference URL [github.com/rapid7/metasploit-framework](github.com/rapid7/metasploit-framework) (and possibly others) refers to something in Go.

```
module: github.com/rapid7/metasploit-framework
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  

cve: CVE-2017-13872
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
