### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2017-14730

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#40]
In [CVE-2017-14730](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2017/14xxx/CVE-2017-14730.json), the reference URL [gitweb.gentoo.org/repo/gentoo.git](gitweb.gentoo.org/repo/gentoo.git) (and possibly others) refers to something in Go.

```
module: gitweb.gentoo.org/repo/gentoo.git
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  The init script in the Gentoo app-admin/logstash-bin package before 5.5.3 and 5.6.x before 5.6.1 has "chown -R" calls for user-writable directory trees, which allows local users to gain privileges by leveraging access to a $LS_USER account for creation of a hard link.

cve: CVE-2017-14730
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
