### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2017-15041

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#41]
In [CVE-2017-15041](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2017/15xxx/CVE-2017-15041.json), the reference URL [Go Standard Library](Go Standard Library) (and possibly others) refers to something in Go.

```
module: Go Standard Library
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  Go before 1.8.4 and 1.9.x before 1.9.1 allows "go get" remote command execution. Using custom domains, it is possible to arrange things so that example.com/pkg1 points to a Subversion repository but example.com/pkg1/pkg2 points to a Git repository. If the Subversion repository includes a Git checkout in its pkg2 directory and some other work is done to ensure the proper ordering of operations, "go get" can be tricked into reusing this Git checkout for the fetch of code from pkg2. If the Subversion repository's Git checkout has malicious commands in .git/hooks/, they will execute on the system running "go get."

cve: CVE-2017-15041
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
