### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2017-15701

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#43]
In [CVE-2017-15701](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2017/15xxx/CVE-2017-15701.json), the reference URL [qpid.apache.org](qpid.apache.org) (and possibly others) refers to something in Go.

```
module: qpid.apache.org
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  In Apache Qpid Broker-J versions 6.1.0 through 6.1.4 (inclusive) the broker does not properly enforce a maximum frame size in AMQP 1.0 frames. A remote unauthenticated attacker could exploit this to cause the broker to exhaust all available memory and eventually terminate. Older AMQP protocols are not affected.

cve: CVE-2017-15701
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
