### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2017-16762

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#45]
In [CVE-2017-16762](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2017/16xxx/CVE-2017-16762.json), the reference URL [github.com/channelcat/sanic](github.com/channelcat/sanic) (and possibly others) refers to something in Go.

```
module: github.com/channelcat/sanic
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  Sanic before 0.5.1 allows reading arbitrary files with directory traversal, as demonstrated by the /static/..%2f substring.

cve: CVE-2017-16762
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
