### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2017-17411

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#46]
In [CVE-2017-17411](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2017/17xxx/CVE-2017-17411.json), the reference URL [github.com/rapid7/metasploit-framework](github.com/rapid7/metasploit-framework) (and possibly others) refers to something in Go.

```
module: github.com/rapid7/metasploit-framework
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  This vulnerability allows remote attackers to execute arbitrary code on vulnerable installations of Linksys WVBR0 WVBR0. Authentication is not required to exploit this vulnerability. The specific flaw exists within the web management portal. The issue lies in the lack of proper validation of user data before executing a system call. An attacker could leverage this vulnerability to execute code with root privileges. Was ZDI-CAN-4892.

cve: CVE-2017-17411
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
