### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2017-17560

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#47]
In [CVE-2017-17560](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2017/17xxx/CVE-2017-17560.json), the reference URL [github.com/rapid7/metasploit-framework](github.com/rapid7/metasploit-framework) (and possibly others) refers to something in Go.

```
module: github.com/rapid7/metasploit-framework
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  An issue was discovered on Western Digital MyCloud PR4100 2.30.172 devices. The web administration component, /web/jquery/uploader/multi_uploadify.php, provides multipart upload functionality that is accessible without authentication and can be used to place a file anywhere on the device's file system. This allows an attacker the ability to upload a PHP shell onto the device and obtain arbitrary code execution as root.

cve: CVE-2017-17560
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
