### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2017-18044

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#48]
In [CVE-2017-18044](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2017/18xxx/CVE-2017-18044.json), the reference URL [github.com/rapid7/metasploit-framework](github.com/rapid7/metasploit-framework) (and possibly others) refers to something in Go.

```
module: github.com/rapid7/metasploit-framework
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  A Command Injection issue was discovered in ContentStore/Base/CVDataPipe.dll in Commvault before v11 SP6. A certain message parsing function inside the Commvault service does not properly validate the input of an incoming string before passing it to CreateProcess. As a result, a specially crafted message can inject commands that will be executed on the target operating system. Exploitation of this vulnerability does not require authentication and can lead to SYSTEM level privilege on any system running the cvd daemon. This is a different vulnerability than CVE-2017-3195.

cve: CVE-2017-18044
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
