### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2017-5677

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#49]
In [CVE-2017-5677](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2017/5xxx/CVE-2017-5677.json), the reference URL [gitweb.gentoo.org/repo/gentoo.git](gitweb.gentoo.org/repo/gentoo.git) (and possibly others) refers to something in Go.

```
module: gitweb.gentoo.org/repo/gentoo.git
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  PEAR HTML_AJAX 0.3.0 through 0.5.7 has a PHP Object Injection Vulnerability in the PHP Serializer. It allows remote code execution. In one viewpoint, the root cause is an incorrect regular expression.

cve: CVE-2017-5677
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
