### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2017-7269

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#50]
In [CVE-2017-7269](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2017/7xxx/CVE-2017-7269.json), the reference URL [github.com/rapid7/metasploit-framework](github.com/rapid7/metasploit-framework) (and possibly others) refers to something in Go.

```
module: github.com/rapid7/metasploit-framework
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  Buffer overflow in the ScStoragePathFromUrl function in the WebDAV service in Internet Information Services (IIS) 6.0 in Microsoft Windows Server 2003 R2 allows remote attackers to execute arbitrary code via a long header beginning with "If: <http://" in a PROPFIND request, as exploited in the wild in July or August 2016.

cve: CVE-2017-7269
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
