### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2017-8932

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#51]
In [CVE-2017-8932](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2017/8xxx/CVE-2017-8932.json), the reference URL [Go Standard Library](Go Standard Library) (and possibly others) refers to something in Go.

```
module: Go Standard Library
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  A bug in the standard library ScalarMult implementation of curve P-256 for amd64 architectures in Go before 1.7.6 and 1.8.x before 1.8.2 causes incorrect results to be generated for specific input points. An adaptive attack can be mounted to progressively extract the scalar input to ScalarMult by submitting crafted points and observing failures to the derive correct output. This leads to a full key recovery attack against static ECDH, as used in popular JWT libraries.

cve: CVE-2017-8932
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
