### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2018-10196

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#52]
In [CVE-2018-10196](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2018/10xxx/CVE-2018-10196.json), the reference URL [gitlab.com/graphviz/graphviz](gitlab.com/graphviz/graphviz) (and possibly others) refers to something in Go.

```
module: gitlab.com/graphviz/graphviz
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  NULL pointer dereference vulnerability in the rebuild_vlists function in lib/dotgen/conc.c in the dotgen library in Graphviz 2.40.1 allows remote attackers to cause a denial of service (application crash) via a crafted file.

cve: CVE-2018-10196
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
