### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2018-16874

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#54]
In [CVE-2018-16874](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2018/16xxx/CVE-2018-16874.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: Go Standard Library (package not identified)
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  In Go before 1.10.6 and 1.11.x before 1.11.3, the "go get" command is vulnerable to directory traversal when executed with the import path of a malicious Go package which contains curly braces (both '{' and '}' characters). Specifically, it is only vulnerable in GOPATH mode, but not in module mode (the distinction is documented at https://golang.org/cmd/go/#hdr-Module_aware_go_get). The attacker can cause an arbitrary filesystem write, which can lead to code execution.

cve: CVE-2018-16874
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
