### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2018-16875

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#55]
In [CVE-2018-16875](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2018/16xxx/CVE-2018-16875.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: Go Standard Library (package not identified)
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  The crypto/x509 package of Go before 1.10.6 and 1.11.x before 1.11.3 does not limit the amount of work performed for each chain verification, which might allow attackers to craft pathological inputs leading to a CPU denial of service. Go TLS servers accepting client certificates and TLS clients are affected.

cve: CVE-2018-16875
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
