### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2018-17143

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#57]
In [CVE-2018-17143](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2018/17xxx/CVE-2018-17143.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: Go Standard Library (package not identified)
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  The html package (aka x/net/html) through 2018-09-17 in Go mishandles <template><tBody><isindex/action=0>, leading to a "panic: runtime error" in inBodyIM in parse.go during an html.Parse call.

cve: CVE-2018-17143
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
