### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2018-17553

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#60]
In [CVE-2018-17553](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2018/17xxx/CVE-2018-17553.json), the reference URL [github.com/rapid7/metasploit-framework](github.com/rapid7/metasploit-framework) (and possibly others) refers to something in Go.

```
module: github.com/rapid7/metasploit-framework
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  An "Unrestricted Upload of File with Dangerous Type" issue with directory traversal in navigate_upload.php in Naviwebs Navigate CMS 2.8 allows authenticated attackers to achieve remote code execution via a POST request with engine=picnik and id=../../../navigate_info.php.

cve: CVE-2018-17553
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
