### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2018-17847

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#61]
In [CVE-2018-17847](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2018/17xxx/CVE-2018-17847.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: Go Standard Library (package not identified)
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  The html package (aka x/net/html) through 2018-09-25 in Go mishandles <svg><template><desc><t><svg></template>, leading to a "panic: runtime error" (index out of range) in (*nodeStack).pop in node.go, called from (*parser).clearActiveFormattingElements, during an html.Parse call.

cve: CVE-2018-17847
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
