### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2018-19572

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#63]
In [CVE-2018-19572](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2018/19xxx/CVE-2018-19572.json), the reference URL [gitlab.com/gitlab-org/gitlab-pages](gitlab.com/gitlab-org/gitlab-pages) (and possibly others) refers to something in Go.

```
module: gitlab.com/gitlab-org/gitlab-pages
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  GitLab CE 8.17 and later and EE 8.3 and later have a symlink time-of-check-to-time-of-use race condition that would allow unauthorized access to files in the GitLab Pages chroot environment. This is fixed in versions 11.5.1, 11.4.8, and 11.3.11.

cve: CVE-2018-19572
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
