### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2018-19583

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#64]
In [CVE-2018-19583](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2018/19xxx/CVE-2018-19583.json), the reference URL [gitlab.com/gitlab-org/gitlab-workhorse](gitlab.com/gitlab-org/gitlab-workhorse) (and possibly others) refers to something in Go.

```
module: gitlab.com/gitlab-org/gitlab-workhorse
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  GitLab CE/EE, versions 8.0 up to 11.x before 11.3.11, 11.4 before 11.4.8, and 11.5 before 11.5.1, would log access tokens in the Workhorse logs, permitting administrators with access to the logs to see another user's token.

cve: CVE-2018-19583
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
