### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2018-6574

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#65]
In [CVE-2018-6574](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2018/6xxx/CVE-2018-6574.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: Go Standard Library (package not identified)
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  Go before 1.8.7, Go 1.9.x before 1.9.4, and Go 1.10 pre-releases before Go 1.10rc2 allow "go get" remote command execution during source code build, by leveraging the gcc or clang plugin feature, because -fplugin= and -plugin= arguments were not blocked.

cve: CVE-2018-6574
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
