### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2018-7187

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#67]
In [CVE-2018-7187](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2018/7xxx/CVE-2018-7187.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: Go Standard Library (package not identified)
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  The "go get" implementation in Go 1.9.4, when the -insecure command-line option is used, does not validate the import path (get/vcs.go only checks for "://" anywhere in the string), which allows remote attackers to execute arbitrary OS commands via a crafted web site.

cve: CVE-2018-7187
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
