### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2018-7890

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#68]
In [CVE-2018-7890](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2018/7xxx/CVE-2018-7890.json), the reference URL [github.com/rapid7/metasploit-framework](github.com/rapid7/metasploit-framework) (and possibly others) refers to something in Go.

```
module: github.com/rapid7/metasploit-framework
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  A remote code execution issue was discovered in Zoho ManageEngine Applications Manager before 13.6 (build 13640). The publicly accessible testCredential.do endpoint takes multiple user inputs and validates supplied credentials by accessing a specified system. This endpoint calls several internal classes, and then executes a PowerShell script. If the specified system is OfficeSharePointServer, then the username and password parameters to this script are not validated, leading to Command Injection.

cve: CVE-2018-7890
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
