### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2018-8065

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#69]
In [CVE-2018-8065](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2018/8xxx/CVE-2018-8065.json), the reference URL [github.com/rapid7/metasploit-framework](github.com/rapid7/metasploit-framework) (and possibly others) refers to something in Go.

```
module: github.com/rapid7/metasploit-framework
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  An issue was discovered in the web server in Flexense SyncBreeze Enterprise 10.6.24. There is a user mode write access violation on the syncbrs.exe memory region that can be triggered by rapidly sending a variety of HTTP requests with long HTTP header values or long URIs.

cve: CVE-2018-8065
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
