### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2018-9866

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#70]
In [CVE-2018-9866](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2018/9xxx/CVE-2018-9866.json), the reference URL [github.com/rapid7/metasploit-framework](github.com/rapid7/metasploit-framework) (and possibly others) refers to something in Go.

```
module: github.com/rapid7/metasploit-framework
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  A vulnerability in lack of validation of user-supplied parameters pass to XML-RPC calls on SonicWall Global Management System (GMS) virtual appliance's, allow remote user to execute arbitrary code. This vulnerability affected GMS version 8.1 and earlier.

cve: CVE-2018-9866
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
