### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2019-10123

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#71]
In [CVE-2019-10123](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2019/10xxx/CVE-2019-10123.json), the reference URL [github.com/rapid7/metasploit-framework](github.com/rapid7/metasploit-framework) (and possibly others) refers to something in Go.

```
module: github.com/rapid7/metasploit-framework
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  SQL Injection in Advanced InfoData Systems (AIS) ESEL-Server 67 (which is the backend for the AIS logistics mobile app) allows an anonymous attacker to execute arbitrary code in the context of the user of the MSSQL database. The default user for the database is the 'sa' user.

cve: CVE-2019-10123
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
