### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2019-11023

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#72]
In [CVE-2019-11023](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2019/11xxx/CVE-2019-11023.json), the reference URL [gitlab.com/graphviz/graphviz](gitlab.com/graphviz/graphviz) (and possibly others) refers to something in Go.

```
module: gitlab.com/graphviz/graphviz
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  The agroot() function in cgraph\obj.c in libcgraph.a in Graphviz 2.39.20160612.1140 has a NULL pointer dereference, as demonstrated by graphml2gv.

cve: CVE-2019-11023
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
