### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2019-12799

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#74]
In [CVE-2019-12799](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2019/12xxx/CVE-2019-12799.json), the reference URL [github.com/rapid7/metasploit-framework](github.com/rapid7/metasploit-framework) (and possibly others) refers to something in Go.

```
module: github.com/rapid7/metasploit-framework
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  In createInstanceFromNamedArguments in Shopware through 5.6.x, a crafted web request can trigger a PHP object instantiation vulnerability, which can result in an arbitrary deserialization if the right class is instantiated. An attacker can leverage this deserialization to achieve remote code execution. NOTE: this issue is a bypass for a CVE-2017-18357 whitelist patch.

cve: CVE-2019-12799
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
