### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2019-14809

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#75]
In [CVE-2019-14809](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2019/14xxx/CVE-2019-14809.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: Go Standard Library (package not identified)
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  net/url in Go before 1.11.13 and 1.12.x before 1.12.8 mishandles malformed hosts in URLs, leading to an authorization bypass in some applications. This is related to a Host field with a suffix appearing in neither Hostname() nor Port(), and is related to a non-numeric port number. For example, an attacker can compose a crafted javascript:// URL that results in a hostname of google.com.

cve: CVE-2019-14809
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
