### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2019-16276

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#76]
In [CVE-2019-16276](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2019/16xxx/CVE-2019-16276.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: Go Standard Library (package not identified)
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  Go before 1.12.10 and 1.13.x before 1.13.1 allow HTTP Request Smuggling.

cve: CVE-2019-16276
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
