### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2019-17596

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#77]
In [CVE-2019-17596](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2019/17xxx/CVE-2019-17596.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: Go Standard Library (package not identified)
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  Go before 1.12.11 and 1.3.x before 1.13.2 can panic upon an attempt to process network traffic containing an invalid DSA public key. There are several attack scenarios, such as traffic from a client to a server that verifies client certificates.

cve: CVE-2019-17596
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
