### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2019-19602

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#78]
In [CVE-2019-19602](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2019/19xxx/CVE-2019-19602.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: Go Standard Library (package not identified)
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  fpregs_state_valid in arch/x86/include/asm/fpu/internal.h in the Linux kernel before 5.4.2, when GCC 9 is used, allows context-dependent attackers to cause a denial of service (memory corruption) or possibly have unspecified other impact because of incorrect fpu_fpregs_owner_ctx caching, as demonstrated by mishandling of signal-based non-cooperative preemption in Go 1.14 prereleases on amd64, aka CID-59c4bd853abc.

cve: CVE-2019-19602
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
