### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2019-5624

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#79]
In [CVE-2019-5624](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2019/5xxx/CVE-2019-5624.json), the reference URL [github.com/rapid7/metasploit-framework](github.com/rapid7/metasploit-framework) (and possibly others) refers to something in Go.

```
module: github.com/rapid7/metasploit-framework
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  Rapid7 Metasploit Framework suffers from an instance of CWE-22, Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal') in the Zip import function of Metasploit. Exploiting this vulnerability can allow an attacker to execute arbitrary code in Metasploit at the privilege level of the user running Metasploit. This issue affects: Rapid7 Metasploit Framework version 4.14.0 and prior versions.

cve: CVE-2019-5624
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
