### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2019-5645

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#80]
In [CVE-2019-5645](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2019/5xxx/CVE-2019-5645.json), the reference URL [github.com/rapid7/metasploit-framework](github.com/rapid7/metasploit-framework) (and possibly others) refers to something in Go.

```
module: github.com/rapid7/metasploit-framework
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  By sending a specially crafted HTTP GET request to a listening Rapid7 Metasploit HTTP handler, an attacker can register an arbitrary regular expression. When evaluated, this malicious handler can either prevent new HTTP handler sessions from being established, or cause a resource exhaustion on the Metasploit server.

cve: CVE-2019-5645
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
