### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2019-6486

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#81]
In [CVE-2019-6486](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2019/6xxx/CVE-2019-6486.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: Go Standard Library (package not identified)
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  Go before 1.10.8 and 1.11.x before 1.11.5 mishandles P-521 and P-384 elliptic curves, which allows attackers to cause a denial of service (CPU consumption) or possibly conduct ECDH private key recovery attacks.

cve: CVE-2019-6486
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
