### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2019-6786

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#82]
In [CVE-2019-6786](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2019/6xxx/CVE-2019-6786.json), the reference URL [gitlab.com/gitlab-org/gitlab-workhorse](gitlab.com/gitlab-org/gitlab-workhorse) (and possibly others) refers to something in Go.

```
module: gitlab.com/gitlab-org/gitlab-workhorse
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  An issue was discovered in GitLab Community and Enterprise Edition before 11.5.8, 11.6.x before 11.6.6, and 11.7.x before 11.7.1. It has Incorrect Access Control (issue 1 of 3). The contents of an LFS object can be accessed by an unauthorized user, if the file size and OID are known.

cve: CVE-2019-6786
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
