### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2019-7401

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#83]
In [CVE-2019-7401](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2019/7xxx/CVE-2019-7401.json), the reference URL [unit.nginx.org](unit.nginx.org) (and possibly others) refers to something in Go.

```
module: unit.nginx.org
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  NGINX Unit before 1.7.1 might allow an attacker to cause a heap-based buffer overflow in the router process with a specially crafted request. This may result in a denial of service (router process crash) or possibly have unspecified other impact.

cve: CVE-2019-7401
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
