### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2019-9634

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#84]
In [CVE-2019-9634](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2019/9xxx/CVE-2019-9634.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: Go Standard Library (package not identified)
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  Go through 1.12 on Windows misuses certain LoadLibrary functionality, leading to DLL injection.

cve: CVE-2019-9634
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
