### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2019-9741

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#85]
In [CVE-2019-9741](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2019/9xxx/CVE-2019-9741.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: Go Standard Library (package not identified)
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  An issue was discovered in net/http in Go 1.11.5. CRLF injection is possible if the attacker controls a url parameter, as demonstrated by the second argument to http.NewRequest with \r\n followed by an HTTP header or a Redis command.

cve: CVE-2019-9741
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
