### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2019-9904

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#86]
In [CVE-2019-9904](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2019/9xxx/CVE-2019-9904.json), the reference URL [gitlab.com/graphviz/graphviz](gitlab.com/graphviz/graphviz) (and possibly others) refers to something in Go.

```
module: gitlab.com/graphviz/graphviz
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  An issue was discovered in lib\cdt\dttree.c in libcdt.a in graphviz 2.40.1. Stack consumption occurs because of recursive agclose calls in lib\cgraph\graph.c in libcgraph.a, related to agfstsubg in lib\cgraph\subg.c.

cve: CVE-2019-9904
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
