### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2020-14039

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#87]
In [CVE-2020-14039](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2020/14xxx/CVE-2020-14039.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: Go Standard Library (package not identified)
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  In Go before 1.13.13 and 1.14.x before 1.14.5, Certificate.Verify may lack a check on the VerifyOptions.KeyUsages EKU requirements (if VerifyOptions.Roots equals nil and the installation is on Windows). Thus, X.509 certificate verification is incomplete.

cve: CVE-2020-14039
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
