### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2020-15586

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#88]
In [CVE-2020-15586](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2020/15xxx/CVE-2020-15586.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: Go Standard Library (package not identified)
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  Go before 1.13.13 and 1.14.x before 1.14.5 has a data race in some net/http servers, as demonstrated by the httputil.ReverseProxy Handler, because it reads a request body and writes a response at the same time.

cve: CVE-2020-15586
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
