### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2020-16845

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#89]
In [CVE-2020-16845](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2020/16xxx/CVE-2020-16845.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: Go Standard Library (package not identified)
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  Go before 1.13.15 and 14.x before 1.14.7 can have an infinite read loop in ReadUvarint and ReadVarint in encoding/binary via invalid inputs.

cve: CVE-2020-16845
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
