### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2020-24553

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#90]
In [CVE-2020-24553](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2020/24xxx/CVE-2020-24553.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: Go Standard Library (package not identified)
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  Go before 1.14.8 and 1.15.x before 1.15.1 allows XSS because text/html is the default for CGI/FCGI handlers that lack a Content-Type header.

cve: CVE-2020-24553
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
