### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2020-29652

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#91]
In [CVE-2020-29652](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2020/29xxx/CVE-2020-29652.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: Go Standard Library (package not identified)
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  A nil pointer dereference in the golang.org/x/crypto/ssh component through v0.0.0-20201203163018-be400aefbc4c for Go allows remote attackers to cause a denial of service against SSH servers.

cve: CVE-2020-29652
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
