### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2020-7664

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#92]
In [CVE-2020-7664](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2020/7xxx/CVE-2020-7664.json), the reference URL [Path is unknown](Path is unknown) (and possibly others) refers to something in Go.

```
module: Path is unknown
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  In all versions of the package github.com/unknwon/cae/zip, the ExtractTo function doesn't securely escape file paths in zip archives which include leading or non-leading "..". This allows an attacker to add or replace files system-wide.

cve: CVE-2020-7664
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
