### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2020-7919

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#93]
In [CVE-2020-7919](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2020/7xxx/CVE-2020-7919.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: Go Standard Library (package not identified)
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  Go before 1.12.16 and 1.13.x before 1.13.7 (and the crypto/cryptobyte package before 0.0.0-20200124225646-8b5121be2f68 for Go) allows attacks on clients (resulting in a panic) via a malformed X.509 certificate.

cve: CVE-2020-7919
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
