### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-20206

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#94]
In [CVE-2021-20206](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2021/20xxx/CVE-2021-20206.json), the reference URL [Path is unknown](Path is unknown) (and possibly others) refers to something in Go.

```
module: Path is unknown
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  An improper limitation of path name flaw was found in containernetworking/cni in versions before 0.8.1. When specifying the plugin to load in the 'type' field in the network configuration, it is possible to use special elements such as "../" separators to reference binaries elsewhere on the system. This flaw allows an attacker to execute other existing binaries other than the cni plugins/types, such as 'reboot'. The highest threat from this vulnerability is to confidentiality, integrity, as well as system availability.

cve: CVE-2021-20206
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
