### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-20848

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#95]
In [CVE-2021-20848](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2021/20xxx/CVE-2021-20848.json), the reference URL [github.com/schollz/rwtxt](github.com/schollz/rwtxt) (and possibly others) refers to something in Go.

```
module: github.com/schollz/rwtxt
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  Cross-site scripting vulnerability in rwtxt versions prior to v1.8.6 allows a remote attacker to inject an arbitrary script via unspecified vectors.

cve: CVE-2021-20848
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
