### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-22166

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#96]
In [CVE-2021-22166](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2021/22xxx/CVE-2021-22166.json), the reference URL [gitlab.com/gitlab-org/labkit](gitlab.com/gitlab-org/labkit) (and possibly others) refers to something in Go.

```
module: gitlab.com/gitlab-org/labkit
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  An attacker could cause a Prometheus denial of service in GitLab 13.7+ by sending an HTTP request with a malformed method

cve: CVE-2021-22166
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
