### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-22565

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#97]
In [CVE-2021-22565](https://github.com/CVEProject/cvelist/tree/42a143637353e9550882ee2846b7d04e813bc7c0/2021/22xxx/CVE-2021-22565.json), the reference URL [github.com/google/exposure-notifications-verification-server](github.com/google/exposure-notifications-verification-server) (and possibly others) refers to something in Go.

```
module: github.com/google/exposure-notifications-verification-server
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  

cve: CVE-2021-22565
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
