### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2021-23409

### ISSUE THREAD

**Issue by jba** [jba/nested-modules#98]
In [CVE-2021-23409](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2021/23xxx/CVE-2021-23409.json), the reference URL [github.com/pires/go-proxyproto](github.com/pires/go-proxyproto) (and possibly others) refers to something in Go.

```
module: github.com/pires/go-proxyproto
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  The package github.com/pires/go-proxyproto before 0.6.0 are vulnerable to Denial of Service (DoS) via creating connections without the proxy protocol header.

cve: CVE-2021-23409
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
